# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-20 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='功能名称')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='地址')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('pnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dbom.Fun', verbose_name='父节点')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='组名')),
                ('remark', models.CharField(blank=True, max_length=5000, null=True, verbose_name='说明')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('fun', models.ManyToManyField(to='dbom.Fun')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeFileDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=64, null=True, verbose_name='上传人')),
                ('upload_time', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('file_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='文件名称')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userGUID', models.CharField(max_length=50, null=True, verbose_name='GUID')),
                ('fullname', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=5000, null=True, verbose_name='说明')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司')),
                ('tell', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('forgetpassword', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改密码地址')),
                ('group', models.ManyToManyField(to='dbom.Group')),
                ('pnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dbom.UserInfo', verbose_name='父节点')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
