# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-22 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=256, verbose_name='客户名称')),
                ('address', models.CharField(blank=True, default='', max_length=256, verbose_name='客户地址')),
                ('contact', models.CharField(blank=True, default='', max_length=128, verbose_name='联系人')),
                ('position', models.CharField(blank=True, default='', max_length=128, verbose_name='职位')),
                ('tel', models.CharField(blank=True, default='', max_length=128, verbose_name='联系电话')),
                ('fax', models.CharField(blank=True, default='', max_length=128, verbose_name='传真')),
                ('email', models.CharField(blank=True, default='', max_length=128, verbose_name='电子邮件')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionOperate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('enddate', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('version', models.CharField(blank=True, default='', max_length=128, verbose_name='Commvault版本')),
                ('host_name', models.CharField(blank=True, default='', max_length=128, verbose_name='OS平台/主机名')),
                ('patch', models.CharField(blank=True, default='', max_length=128, verbose_name='补丁')),
                ('all_client', models.IntegerField(default=0, verbose_name='全部客户端')),
                ('offline_client', models.IntegerField(default=0, verbose_name='脱机客户端')),
                ('offline_client_content', models.CharField(blank=True, default='', max_length=512, verbose_name='脱机故障内容')),
                ('backup_time', models.IntegerField(default=0, verbose_name='备份次数')),
                ('fail_time', models.IntegerField(default=0, verbose_name='失败次数')),
                ('fail_log', models.CharField(blank=True, default='', max_length=512, verbose_name='失败日志')),
                ('total_capacity', models.IntegerField(default=0, verbose_name='存储总容量')),
                ('used_capacity', models.IntegerField(default=0, verbose_name='已用容量')),
                ('increase_capacity', models.IntegerField(default=0, verbose_name='平均每月增长量')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='报告标题')),
                ('cur_date', models.DateTimeField(null=True, verbose_name='巡检日期')),
                ('engineer', models.CharField(blank=True, default='', max_length=128, verbose_name='责任工程师')),
                ('last_date', models.DateTimeField(null=True, verbose_name='上次巡检日期')),
                ('next_date', models.DateTimeField(null=True, verbose_name='预计下次巡检日期')),
                ('hardware_error', models.IntegerField(choices=[(1, '正常'), (0, '异常')], default=1, verbose_name='是否硬件故障')),
                ('hardware_error_content', models.CharField(blank=True, default='', max_length=512, verbose_name='硬件故障备注')),
                ('software_error', models.IntegerField(choices=[(1, '正常'), (0, '异常')], default=1, verbose_name='是否软件故障')),
                ('software_error_content', models.CharField(blank=True, default='', max_length=512, verbose_name='软件故障备注')),
                ('aging_plan_run', models.IntegerField(choices=[(1, '正常'), (0, '异常')], default=1, verbose_name='数据时效计划运行情况')),
                ('backup_plan_run', models.IntegerField(choices=[(1, '正常'), (0, '异常')], default=1, verbose_name='数据备份计划运行情况')),
                ('backup_plan_run_remark', models.CharField(blank=True, default='', max_length=512, verbose_name='备份计划运行备注')),
                ('running_status', models.IntegerField(choices=[(1, '正常'), (0, '异常')], default=1, verbose_name='报告运行情况')),
                ('running_remark', models.CharField(blank=True, default='', max_length=512, verbose_name='运行情况备注')),
                ('client_add', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='最近是否打算要增加新的客户端')),
                ('client_add_remark', models.CharField(blank=True, default='', max_length=512, verbose_name='新增客户端备注')),
                ('backup_plan', models.IntegerField(choices=[(1, '正常'), (0, '异常')], default=1, verbose_name='备份计划')),
                ('backup_plan_remark', models.CharField(blank=True, default='', max_length=512, verbose_name='备份计划')),
                ('aging_plan', models.IntegerField(choices=[(1, '正常'), (0, '异常')], default=1, verbose_name='数据时效计划')),
                ('aging_plan_remark', models.CharField(blank=True, default='', max_length=512, verbose_name='时效计划备注')),
                ('error_send', models.IntegerField(choices=[(1, '有'), (0, '否')], default=1, verbose_name='有否发给cvadmin用户的错误报告')),
                ('error_send_remark', models.CharField(blank=True, default='', max_length=512, verbose_name='错误报告备注')),
                ('cdr_running', models.IntegerField(choices=[(1, '正常'), (0, '异常')], default=1, verbose_name='CDR运行情况')),
                ('cdr_running_remark', models.CharField(blank=True, default='', max_length=512, verbose_name='CDR运行备注')),
                ('media_run', models.IntegerField(choices=[(1, '正常'), (0, '异常')], default=1, verbose_name='备份介质运行状态')),
                ('media_run_remark', models.CharField(blank=True, default='', max_length=512, verbose_name='备份介质运行备注')),
                ('extra_error_content', models.CharField(blank=True, default='', max_length=2000, verbose_name='其他错误报告内容')),
                ('suggestion_and_summary', models.CharField(blank=True, default='', max_length=2000, verbose_name='其他错误报告内容')),
                ('client_sign', models.DateTimeField(null=True, verbose_name='客户签字日期')),
                ('engineer_sign', models.DateTimeField(null=True, verbose_name='维修工程师签字日期')),
                ('client_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbom.ClientData', verbose_name='客户资料')),
                ('inspection_operate', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbom.InspectionOperate', verbose_name='巡检操作')),
            ],
        ),
    ]
