# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-23 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0002_clientdata_inspectionoperate_inspectionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='aging_plan_run_remark',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='时效计划运行备注'),
        ),
    ]
