# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0003_inspectionreport_aging_plan_run_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionoperate',
            name='enddate',
            field=models.DateField(null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='inspectionoperate',
            name='startdate',
            field=models.DateField(null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='client_sign',
            field=models.DateField(null=True, verbose_name='客户签字日期'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='cur_date',
            field=models.DateField(null=True, verbose_name='巡检日期'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='engineer_sign',
            field=models.DateField(null=True, verbose_name='维修工程师签字日期'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='last_date',
            field=models.DateField(null=True, verbose_name='上次巡检日期'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='next_date',
            field=models.DateField(null=True, verbose_name='预计下次巡检日期'),
        ),
    ]
