# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-23 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0004_auto_20190423_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='state',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='inspectionoperate',
            name='state',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='state',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='状态'),
        ),
    ]
