# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-26 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('dbom', '0008_auto_20190428_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='RsyncConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '备份中'), (2, '关闭'), (3, '开启')], default=3, verbose_name='定时任务状态')),
                ('log', models.CharField(blank=True, max_length=512, verbose_name='配置失败日志')),
                ('state', models.CharField(blank=True, default='', max_length=16, verbose_name="逻辑删除:'9'")),
            ],
        ),
        migrations.CreateModel(
            name='RsyncHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=128, verbose_name='主机ip')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('status', models.IntegerField(choices=[(1, '已安装'), (2, '关机'), (3, '失败'), (4, '未安装')], default=4, verbose_name='主机状态/Rsync安装状态')),
                ('log', models.CharField(blank=True, max_length=512, verbose_name='安装错误日志')),
                ('state', models.CharField(blank=True, default='', max_length=16, verbose_name="逻辑删除:'9'")),
            ],
        ),
        migrations.CreateModel(
            name='RsyncModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128, verbose_name='模块名称')),
                ('rsync_path', models.CharField(max_length=512, verbose_name='Rsync的文件路径')),
                ('state', models.CharField(blank=True, default='', max_length=16, verbose_name="逻辑删除:'9'")),
            ],
        ),
        migrations.CreateModel(
            name='RsyncRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, verbose_name='开始时间')),
                ('endtime', models.DateTimeField(blank=True, verbose_name='结束时间')),
                ('log', models.CharField(blank=True, max_length=512, verbose_name='备份失败日志')),
                ('status', models.IntegerField(choices=[(1, '成功'), (2, '失败')], default=1, verbose_name='备份状态')),
                ('rsync_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbom.RsyncConfig', verbose_name='Rsync配置')),
            ],
        ),
        migrations.AddField(
            model_name='rsyncconfig',
            name='backup_host',
            field=models.ManyToManyField(related_name='rsyncconfig_backup_host', to='dbom.RsyncHost', verbose_name='备机'),
        ),
        migrations.AddField(
            model_name='rsyncconfig',
            name='dj_crontab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djcelery.CrontabSchedule', verbose_name='定时任务'),
        ),
        migrations.AddField(
            model_name='rsyncconfig',
            name='main_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbom.RsyncHost', verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='rsyncconfig',
            name='rsync_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbom.RsyncModel', verbose_name='Rsync备份模块'),
        ),
    ]
