# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-26 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0009_auto_20190626_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsynchost',
            name='status',
        ),
        migrations.AddField(
            model_name='rsynchost',
            name='install_status',
            field=models.IntegerField(choices=[(1, '已安装'), (2, '未安装'), (3, '失败'), (4, '未知')], default=1, verbose_name='Rsync安装状态'),
        ),
        migrations.AddField(
            model_name='rsynchost',
            name='server_status',
            field=models.IntegerField(choices=[(1, '开启'), (2, '关闭')], default=1, verbose_name='服务器状态'),
        ),
    ]
