# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-27 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0010_auto_20190626_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsyncconfig',
            name='status',
            field=models.IntegerField(choices=[(1, '关闭'), (2, '开启')], default=1, verbose_name='定时任务状态'),
        ),
    ]
