# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-27 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0011_auto_20190627_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsyncconfig',
            name='rsync_model',
        ),
        migrations.AddField(
            model_name='rsyncmodel',
            name='rsync_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbom.RsyncConfig', verbose_name='Rsync配置'),
        ),
    ]
