# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0012_auto_20190627_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsyncconfig',
            name='log',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='配置失败日志'),
        ),
    ]
