# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-28 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0013_auto_20190627_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsyncconfig',
            name='status',
        ),
    ]
