# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-28 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('dbom', '0014_remove_rsyncconfig_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsyncconfig',
            name='dj_crontab',
        ),
        migrations.AddField(
            model_name='rsyncconfig',
            name='dj_periodictask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djcelery.PeriodicTask', verbose_name='定时任务'),
        ),
    ]
