# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-01 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0015_auto_20190628_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsynchost',
            name='install_status',
        ),
        migrations.RemoveField(
            model_name='rsynchost',
            name='server_status',
        ),
    ]
