# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-03 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0017_rsyncrecord_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsyncconfig',
            name='dj_periodictask',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='djcelery.PeriodicTask', verbose_name='定时任务'),
        ),
    ]
