# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0019_auto_20190704_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsynchost',
            name='status',
            field=models.IntegerField(choices=[(1, '服务启动'), (2, '服务关闭')], default=2, verbose_name='Web服务状态'),
        ),
    ]
