# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-22 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0020_rsynchost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsyncconfig',
            name='backup_host',
        ),
        migrations.RemoveField(
            model_name='rsyncmodel',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='rsyncmodel',
            name='rsync_path',
        ),
        migrations.AddField(
            model_name='rsyncmodel',
            name='dest_path',
            field=models.CharField(default='', max_length=512, verbose_name='终端路径'),
        ),
        migrations.AddField(
            model_name='rsyncmodel',
            name='main_path',
            field=models.CharField(default='', max_length=512, verbose_name='源端路径'),
        ),
        migrations.AlterField(
            model_name='rsyncconfig',
            name='main_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbom.RsyncHost', verbose_name='源端'),
        ),
    ]
