# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-22 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0021_auto_20190722_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsyncconfig',
            name='backup_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_host', to='dbom.RsyncHost', verbose_name='终端'),
        ),
        migrations.AlterField(
            model_name='rsyncconfig',
            name='main_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_host', to='dbom.RsyncHost', verbose_name='源端'),
        ),
    ]
