# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-22 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0022_auto_20190722_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsyncmodel',
            name='model_name',
            field=models.CharField(default='', max_length=128, verbose_name='模块名称'),
        ),
    ]
