# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0024_auto_20190723_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsyncrecord',
            name='log',
            field=models.CharField(blank=True, max_length=5000, verbose_name='备份失败日志'),
        ),
    ]
