# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-16 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0026_auto_20190816_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionreport',
            old_name='per_week_capacity',
            new_name='period_capacity',
        ),
    ]
