# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-16 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0027_auto_20190816_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionoperate',
            name='backup_time',
        ),
        migrations.RemoveField(
            model_name='inspectionoperate',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='inspectionoperate',
            name='fail_log',
        ),
        migrations.RemoveField(
            model_name='inspectionoperate',
            name='fail_time',
        ),
        migrations.RemoveField(
            model_name='inspectionoperate',
            name='startdate',
        ),
    ]
