# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-16 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0028_auto_20190816_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionreport',
            name='media_run',
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='auxiliary_copy',
            field=models.CharField(blank=True, default='', max_length=640, verbose_name='辅助拷贝'),
        ),
    ]
