# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0029_auto_20190816_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionoperate',
            name='increase_capacity',
        ),
        migrations.RemoveField(
            model_name='inspectionoperate',
            name='total_capacity',
        ),
        migrations.RemoveField(
            model_name='inspectionoperate',
            name='used_capacity',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='library_server',
        ),
        migrations.AddField(
            model_name='inspectionoperate',
            name='library_server',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='介质服务器'),
        ),
    ]
