# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbom', '0030_auto_20190816_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionoperate',
            name='library_server',
            field=models.TextField(blank=True, default='', verbose_name='介质服务器'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='agent_backup_status',
            field=models.TextField(blank=True, default='', verbose_name='各类agent备份情况'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='suggestion_and_summary',
            field=models.CharField(blank=True, default='', max_length=640, verbose_name='建议和总结'),
        ),
    ]
